// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjHxYhFRRuoRps5Z3xAQ8f8OK_K_wWfc',
    appId: '1:804569389216:web:3eb46494b9e9c604a9d1c5',
    messagingSenderId: '804569389216',
    projectId: 'chatapp-8df8b',
    authDomain: 'chatapp-8df8b.firebaseapp.com',
    storageBucket: 'chatapp-8df8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaQCLT9WYiXKLpX3G8fr7xFyL-sFJOFg',
    appId: '1:804569389216:android:7b2e3d8be8898dcba9d1c5',
    messagingSenderId: '804569389216',
    projectId: 'chatapp-8df8b',
    storageBucket: 'chatapp-8df8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIxDn3JOBHhNLGokOs8RDhVWEVr0Y7b8',
    appId: '1:804569389216:ios:1f7df507d9b811b6a9d1c5',
    messagingSenderId: '804569389216',
    projectId: 'chatapp-8df8b',
    storageBucket: 'chatapp-8df8b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIxDn3JOBHhNLGokOs8RDhVWEVr0Y7b8',
    appId: '1:804569389216:ios:1f7df507d9b811b6a9d1c5',
    messagingSenderId: '804569389216',
    projectId: 'chatapp-8df8b',
    storageBucket: 'chatapp-8df8b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDjHxYhFRRuoRps5Z3xAQ8f8OK_K_wWfc',
    appId: '1:804569389216:web:0890b63d6a9c1bf0a9d1c5',
    messagingSenderId: '804569389216',
    projectId: 'chatapp-8df8b',
    authDomain: 'chatapp-8df8b.firebaseapp.com',
    storageBucket: 'chatapp-8df8b.appspot.com',
  );

}